### ISSUE TITLE
Timer doesn't ring when time is over

### ISSUE THREAD

**Issue by mgerzabek** [dankimio/Tomato-Flow#2]
Hi Dan,
I installed your awesome App on iPhone 6s+ today and started to work with it. When the pomodoro is over, nothing happens that reminds me that the time IS actually over and I should do a break. Is this on intention? I'd like to have a tone that reminds me, that time is over. And I'd also like to ring if my phone is in silent mode, like the Apple Watch is doing für general timers.
Thanks for the App,
Michael

**Comment by dankimio** [comment]
Thanks for the report! The bug should be fixed in the new version.
