### ISSUE TITLE
Background behavior

### ISSUE THREAD

**Issue by nurlan-dzhavadov** [dankimio/Tomato-Flow#3]
Hello, Dan!

Thanks for your app! I have one problem: the timer stops when app enters background. I tried to find solution on the Internet, but with no success. 
Can you please help to solve this problem?

**Comment by dankimio** [comment]
Hi @dvlpd, thanks for opening up the issue!

I haven't worked on this project for a long time. Would you mind messaging me on Telegram ([t.me/dankimio](https://t.me/dankimio)) or emailing me (email in profile), so that we can figure this out faster?
